# Generated by Django 5.2 on 2025-04-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Город')),
            ],
            options={
                'verbose_name': '02. Город',
                'verbose_name_plural': '02. Город',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Страна')),
            ],
            options={
                'verbose_name': '01. Страна',
                'verbose_name_plural': '01. Страна',
                'db_table': 'country',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '03. Пользователи', 'verbose_name_plural': '03. Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.country', verbose_name='Страна'),
        ),
    ]
