# Generated by Django 5.2 on 2025-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='проверочный код'),
        ),
    ]
