# Generated by Django 5.2 on 2025-04-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('item_name', models.TextField(verbose_name='Название объекта')),
                ('item_class', models.IntegerField(verbose_name='Класс объекта')),
                ('year_first_release', models.IntegerField(blank=True, null=True, verbose_name='Год первого выпуска')),
                ('year_last_release', models.IntegerField(blank=True, null=True, verbose_name='Год последнего выпуска')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('item_dim', models.TextField(blank=True, null=True, verbose_name='Размеры объекта')),
                ('pack_dim', models.TextField(blank=True, null=True, verbose_name='Размеры упаковки')),
                ('flat_dim', models.TextField(blank=True, null=True, verbose_name='Плоские размеры')),
                ('stud_dim', models.TextField(blank=True, null=True, verbose_name='Размеры шпильки')),
                ('instructions', models.BooleanField(blank=True, null=True, verbose_name='Наличие инструкций')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'db_table': 'obj',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('collection_name', models.TextField(blank=True, null=True, verbose_name='Название коллекции')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер коллекции')),
            ],
            options={
                'verbose_name': 'Тематическая коллекция',
                'verbose_name_plural': 'Тематические коллекции',
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Alternate',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='brick_main.obj', verbose_name='Основной объект')),
                ('item_id', models.CharField(blank=True, max_length=12, null=True, verbose_name='Альтернативный идентификатор')),
            ],
            options={
                'verbose_name': 'Альтернативный идентификатор',
                'verbose_name_plural': 'Альтернативные идентификаторы',
                'db_table': 'alternate',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(verbose_name='Цвет')),
                ('address', models.TextField(blank=True, null=True, verbose_name='URL изображения')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brick_main.obj', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'images',
                'unique_together': {('item', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_class', models.IntegerField(verbose_name='Класс набора')),
                ('part_class', models.IntegerField(verbose_name='Класс части')),
                ('part_count', models.IntegerField(blank=True, null=True, verbose_name='Количество частей')),
                ('color', models.TextField(verbose_name='Цвет')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_part', to='brick_main.obj', verbose_name='Часть')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_set', to='brick_main.obj', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'db_table': 'links',
                'indexes': [models.Index(fields=['set'], name='links_set_id_988eee_idx'), models.Index(fields=['part'], name='links_part_id_d4777d_idx')],
                'unique_together': {('set', 'part', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ThemeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_links', to='brick_main.theme', verbose_name='Родительская коллекция')),
                ('low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_links', to='brick_main.theme', verbose_name='Дочерняя коллекция')),
            ],
            options={
                'verbose_name': 'Связь тематических коллекций',
                'verbose_name_plural': 'Связи тематических коллекций',
                'db_table': 'theme_links',
                'indexes': [models.Index(fields=['high'], name='theme_links_high_id_bd304a_idx'), models.Index(fields=['low'], name='theme_links_low_id_7961d0_idx')],
                'unique_together': {('high', 'low')},
            },
        ),
        migrations.CreateModel(
            name='ThemeObjLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_obj_links', to='brick_main.theme', verbose_name='Коллекция')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_obj_links', to='brick_main.obj', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Связь коллекции и объекта',
                'verbose_name_plural': 'Связи коллекций и объектов',
                'db_table': 'theme_obj_links',
                'indexes': [models.Index(fields=['high'], name='theme_obj_l_high_id_414ff8_idx'), models.Index(fields=['obj'], name='theme_obj_l_obj_id_5e20fd_idx')],
                'unique_together': {('high', 'obj')},
            },
        ),
    ]
