# Generated by Django 5.2 on 2025-04-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_customuser_verification_code'),
        ('brick_main', '0002_color_knowncolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип валюты',
                'verbose_name_plural': 'Тип валюты',
                'db_table': 'valyuta',
            },
        ),
        migrations.CreateModel(
            name='ObjProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('image', models.URLField(blank=True, null=True, verbose_name='URL-адрес изображения')),
                ('quantity', models.CharField(max_length=250, verbose_name='Количество')),
                ('condition', models.CharField(blank=True, choices=[('новое', 'Новый'), ('б/у:', 'б/у:')], max_length=100, null=True, verbose_name='Состояние')),
                ('country', models.ManyToManyField(blank=True, null=True, to='authen.country', verbose_name='Продавец отправляет товар')),
                ('obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_main.obj', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Объект продукта',
                'verbose_name_plural': 'Объект продукта',
                'db_table': 'obj_product',
            },
        ),
        migrations.CreateModel(
            name='ObjProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цена')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_main.currency', verbose_name='Валюта')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='brick_main.objproduct', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Цена продукта',
                'verbose_name_plural': 'Цена продукта',
                'db_table': 'product_price',
            },
        ),
    ]
