# Generated by Django 5.2 on 2025-04-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick_main', '0003_currency_objproduct_objproductprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('onwer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Вишлисты',
                'verbose_name_plural': 'Вишлисты',
                'db_table': 'wanted_list',
            },
        ),
        migrations.CreateModel(
            name='WantedListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_main.objproduct', verbose_name='продукта')),
                ('wanted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wanted_product', to='brick_main.wantedlist', verbose_name='Вишлисты')),
            ],
            options={
                'verbose_name': 'Вишлисты продукт',
                'verbose_name_plural': 'Вишлисты продукта',
                'db_table': 'wanted_list_product',
            },
        ),
    ]
