# Generated by Django 5.2 on 2025-04-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick_main', '0005_rename_onwer_wantedlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedlistproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_main.color', verbose_name='Цвета'),
        ),
    ]
