# Generated by Django 5.2 on 2025-04-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_customuser_verification_code'),
        ('brick_main', '0006_wantedlistproduct_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Службы доставки',
                'verbose_name_plural': 'Службы доставки',
                'db_table': 'deliverys',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес магазина')),
                ('is_openid', models.BooleanField(default=False, verbose_name='Временно закрыт')),
                ('country', models.ManyToManyField(blank=True, to='authen.country', verbose_name='Выбор, в какие страны отправляешь')),
                ('currency', models.ManyToManyField(blank=True, to='brick_main.currency', verbose_name='Валюта магазина')),
                ('delivery_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_main.deliverys', verbose_name='Доставка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
                'db_table': 'shops',
            },
        ),
        migrations.AddField(
            model_name='objproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brick_main.shops', verbose_name='Магазин'),
        ),
    ]
