# Generated by Django 5.2 on 2025-04-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick_main', '0008_objproduct_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый заказ')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brick_main.shops', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Число')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_product', to='brick_main.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brick_main.objproduct', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказать продукцию',
                'verbose_name_plural': 'Заказать продукцию',
                'db_table': 'order_item',
            },
        ),
    ]
