# Generated by Django 5.1.6 on 2025-03-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_obj_id'),
        ('users', '0002_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_users', to='database.obj', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_users', to='database.obj', verbose_name='Вишлист'),
        ),
    ]
