# Generated by Django 5.1.7 on 2025-03-18 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('database', '0002_alter_obj_id'),
        ('users', '0003_customuser_collection_customuser_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Предмет вишлиста',
                'verbose_name_plural': 'Предметы вишлиста',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['nickname'], name='users_custo_nicknam_66f25c_idx'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.obj'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'obj')},
        ),
    ]
