# Generated by Django 5.1.7 on 2025-03-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wishlistitem_alter_customuser_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wishlist',
        ),
    ]
