# Generated by Django 5.1.7 on 2025-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_obj_id'),
        ('users', '0005_remove_customuser_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='color',
            field=models.CharField(default='Default', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'obj', 'color')},
        ),
    ]
