# Generated by Django 5.1.7 on 2025-03-18 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_obj_id'),
        ('users', '0006_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Default', max_length=50, verbose_name='Цвет')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.obj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предмет коллекции',
                'verbose_name_plural': 'Предметы коллекции',
                'unique_together': {('user', 'obj', 'color')},
            },
        ),
    ]
