# Generated by Django 5.1.7 on 2025-03-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_nicknam_66f25c_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
    ]
