# Generated by Django 5.1.7 on 2025-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_users_custo_nicknam_66f25c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='buyer', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
