# Generated by Django 5.1.7 on 2025-03-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('KZT', 'Казахстанский тенге'), ('BYN', 'Белорусский рубль')], default='RUB', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('be', 'Белорусский')], default='ru', max_length=10, verbose_name='Язык'),
        ),
    ]
