# Generated by Django 5.1.7 on 2025-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('database', '0004_delete_currency_delete_language_delete_usergroup'),
        ('users', '0013_alter_customuser_currency_alter_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['nickname'], name='users_custo_nicknam_66f25c_idx'),
        ),
    ]
