# Generated by Django 5.1.7 on 2025-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_users_custo_nicknam_66f25c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=20, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=20, verbose_name='Язык'),
        ),
    ]
