# Generated by Django 5.1.7 on 2025-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('KZ', 'Казахстан'), ('BY', 'Беларусь')], default='RU', max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
