# Generated by Django 5.1.6 on 2025-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
