# Generated by Django 5.1.7 on 2025-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_currency_language_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
